### ISSUE TITLE
How to reproduce the results on office-home?

### ISSUE THREAD

**Issue by SkeletonOne** [Albert0147/G-SFDA#1]
It seems that we need the split of the train/test of the source/target datasets for office-home in the utils.py, could you provide the txt files?

**Comment by Albert0147** [comment]
Just as VisDA, we randomly split them (only for source), check this [line](https://github.com/Albert0147/G-SFDA/blob/c5f35fdfa373c2e3f1e4b66bb1ad323d82eede57/utils.py#L312) in utils.py

**Comment by SkeletonOne** [comment]
@Albert0147 Thanks for your reply. I am still a little bit confused:
1. I need to go through this [line](https://github.com/Albert0147/G-SFDA/blob/c5f35fdfa373c2e3f1e4b66bb1ad323d82eede57/utils.py#L305-L308) then randomly split them;
2. If I have a different split setting, I may get different results from your published results.

**Comment by Albert0147** [comment]
Yeah, that could happen, especially If the datasets are imbalanced, since we found different performance of source model can lead to different target performance after adaptation. But for VisDA and Office-Home, the difference should be small if using different splitting (*i.e.*, with different random seeds).

**Comment by SkeletonOne** [comment]
@Albert0147 Got it, Thanks!
